sudo: required
services:
  - docker

before_install:
  - docker build -t hundalrs/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run hundalrs/react-test npm test -- --coverage

#after_success:
script:
  - docker build -t hundalrs/multi-client ./client
  - docker build -t hundalrs/multi-nginx ./nginx
  - docker build -t hundalrs/multi-server .
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push hundalrs/multi-client
  - docker push hundalrs/multi-nginx
  - docker push hundalrs/multi-server

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: HiredDev
  env: Hireddev-env
  bucket_name: elasticbeanstalk-us-east-2-384630562796
  bucket_path: HiredDev
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
